
---
apiVersion: v1
kind: Pod
metadata:
  name: testpod
  namespace: dev
spec:
  serviceAccountName: dev-sa
  containers:
    - name: test
      image: bitnami/kubectl:latest
      command: ["sleep", "3600"]
